version: '3.8'

services:
  web:
    image: nginx:1.25
    container_name: web-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - web-app-net
    restart: always

networks:
  web-app-net:
    driver: bridge
