version: '3.8'

services:
  nginx:
    image: nginx:1.25
    container_name: web-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - web-app-net

networks:
  web-app-net:
    driver: bridge
