version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./:/etc/prometheus/
      - ./alertmanager/:/etc/prometheus/
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - "9093:9093"