global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporters'
    static_configs:
      - targets:
          - "172.16.1.10:9100"  # control
          - "172.16.1.20:9100"  # web
          - "172.16.1.30:9100"  # db
          - "172.16.1.40:9100"  # storage-server1
          - "172.16.1.50:9100"  # storage-server2
          - "172.16.1.60:9100"  # monitoring
          - "172.16.1.70:9100"  # app
