global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporters'
    static_configs:
      - targets: ["172.16.1.10:9100"]
        labels:
          instance: "control"

      - targets: ["172.16.1.20:9100"]
        labels:
          instance: "web"

      - targets: ["172.16.1.30:9100"]
        labels:
          instance: "db"

      - targets: ["172.16.1.40:9100"]
        labels:
          instance: "storage1"

      - targets: ["172.16.1.50:9100"]
        labels:
          instance: "storage2"

      - targets: ["172.16.1.60:9100"]
        labels:
          instance: "monitoring"

      - targets: ["172.16.1.70:9100"]
        labels:
          instance: "app"

rule_files:
  - "rules/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
