version: '3.8'

services:
  proxy:
    image: nginx:1.25
    container_name: web-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - web-net

  web1:
    image: nginx:1.25
    container_name: web1
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - web-net

  web2:
    image: nginx:1.25
    container_name: web2
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - web-net

networks:
  web-net:
    driver: bridge
