---
- name: Configure Grafana dashboards and data sources
  hosts: monitoring
  become: false
  vars:
    grafana_host: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "test123"
    dashboard_url: "https://grafana.com/api/dashboards/1860/revisions/34/download"
    dashboard_file_path: "/tmp/node_exporter_full.json"

  tasks:
    - name: Wait for Grafana to be available
      uri:
        url: "{{ grafana_host }}/api/health"
        method: GET
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        status_code: 200
      register: grafana_health
      until: grafana_health.status == 200
      retries: 10
      delay: 5

    - name: Add Prometheus data source to Grafana
      uri:
        url: "{{ grafana_host }}/api/datasources"
        method: POST
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: Prometheus
          type: prometheus
          access: proxy
          url: http://localhost:9090
          isDefault: true
      register: add_prometheus_response
      failed_when: add_prometheus_response.status not in [200, 409]  # 409 = already exists

    - name: Download Node Exporter Full dashboard JSON
      get_url:
        url: "{{ dashboard_url }}"
        dest: "{{ dashboard_file_path }}"

    - name: Import Node Exporter Full dashboard
      uri:
        url: "{{ grafana_host }}/api/dashboards/import"
        method: POST
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          dashboard: "{{ lookup('file', dashboard_file_path) | from_json }}"
          overwrite: true
          inputs:
            - name: "DS_PROMETHEUS"
              type: "datasource"
              pluginId: "prometheus"
              value: "Prometheus"
