---
- name: GlusterFS Setup Playbook (Multi-volume)
  hosts: storage
  become: true

  vars:
    brick_path: /gluster/brick1
    volumes:
      - { name: db1 }
      - { name: db2 }
      - { name: web }
      - { name: app }
      - { name: monitoring }
      
  tasks:

    - name: GlusterFS 설치
      apt:
        name: glusterfs-server
        state: present
        update_cache: yes

    - name: GlusterFS 시작 및 부팅 시 자동 시작
      systemd:
        name: glusterd
        state: started
        enabled: true

    #  실질적인 저장소
    - name: brick 디렉토리 생성
      file:
        path: "{{ brick_path }}/{{ item.name }}"
        state: directory
        owner: user1
        group: user1
        mode: '0777'
      loop: "{{ volumes }}"

    - name: 로그 저장 디렉토리 생성
      file:
        path: "{{ brick_path }}/{{ item.name }}/logs"
        state: absent
        mode: '0777'
      loop: "{{ volumes }}"
      when: item.name in ['web', 'app', 'monitoring']

#피어1,2를 하나로 묶는 작업
    - name: Gluster 피어 프로브 (스토리지1에서만 실행)
      shell: |
        gluster peer probe {{ hostvars['storage-server2']['ansible_host'] }}
      when: inventory_hostname == 'storage-server1'

    - name: 볼륨 생성 (스토리지1에서만 실행)
      shell: |
       if ! gluster volume info {{ item.name }} >/dev/null 2>&1; then
        gluster volume create {{ item.name }} replica 2 \
        172.16.1.40:{{ brick_path }}/{{ item.dir | default(item.name) }} \
        172.16.1.50:{{ brick_path }}/{{ item.dir | default(item.name) }} \
        force
       fi
      when: inventory_hostname == 'storage-server1'
      loop: "{{ volumes }}"
#만들어진 볼륨을 실제로 작동 시키는 단계 이것을 해야 클라이언트가 mount 명령으로 접근 가능
#force 없으면 진행이 안된다 이유는 볼륨 생성시 생성하겠냐고 뜨는데 ansible로 자동 생성이 이게 안보여서 force를 해야 yes가 된다

    - name: 볼륨 시작 (스토리지1에서만 실행)
      shell: |
        if ! gluster volume info {{ item.name }} | grep -q 'Status: Started'; then
          gluster volume start {{ item.name }}
        fi
      when: inventory_hostname == 'storage-server1'
      loop: "{{ volumes }}"

### 클라이언트에서 할 것

#- name: 마운트 지점 생성
#  file:
#    path: "{{ item.mount }}"
#    state: directory

#- name: GlusterFS 볼륨 마운트 예시시
#  mount:
#    path: "/mnt/web/logs"
#    src: "172.16.1.40:gluster/brick/web-logs"
#    fstype: glusterfs
#    opts: defaults,_netdev
#    state: mounted