---
- name: 스토리지 서버 환경 구성 (NFS 서버)
  hosts: storage_server
  become: true

  vars:
    shared_db1_dir: /mnt/shared/db1
    shared_db2_dir: /mnt/shared/db2
    shared_webapp_dir: /mnt/shared/webapp
    shared_monitoring_dir: /mnt/shared/monitoring
    allowed_client_network: # NFS 클라이언트 IP 대역
      - 172.16.1.20
      - 172.16.1.30
      - 172.16.1.60

  tasks:
    - name: NFS 서버 패키지 설치
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes
      tags: nfs

    - name: 공유 디렉토리 생성1 db
      file:
        path: "{{ shared_db_dir }}"
        state: directory
        owner: user1
        group: user1
        mode: '0777'
      tags: nfs

    - name: 공유 디렉토리 생성2 WebApp
      file:
        path: "{{ shared_dir }}"
        state: directory
        owner: user1
        group: user1
        mode: '0777'
      tags: nfs

    - name: 공유 디렉토리 생성3 monitoring
      file:
        path: "{{ shared_dir }}"
        state: directory
        owner: user1
        group: user1
        mode: '0777'
      tags: nfs

    - name: /etc/exports 설정
      blockinfile:
        path: /etc/exports
        block: |
          {{ shared_dir }} {{ allowed_client_network }}(rw,sync,no_subtree_check,no_root_squash)
      tags: nfs

    - name: NFS 서비스 재시작
      service:
        name: nfs-kernel-server
        state: restarted
      tags: nfs

    - name: 방화벽 - NFS 포트 허용
      ufw:
        rule: allow
        port: 2049
        proto: tcp
      tags: firewall