---
- name: Deploy cAdvisor on all target servers
  hosts: web, db, app
  become: true
  tasks:
    # - name: Install Docker (if not installed)
    #   apt:
    #     name: docker.io
    #     state: present
    #     update_cache: yes

    # - name: Start and enable Docker service
    #   systemd:
    #     name: docker
    #     enabled: yes
    #     state: started

    - name: Deploy cAdvisor container
      docker_container:
        name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:ro"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
