---
- name: Deploy Web Cluster with Proxy
  hosts: web
  become: true

  vars:
    deploy_root: /home/user1/web_deploy
    local_root: ../../infra-components/web

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: common

    - name: Create deployment directory
      file:
        path: "{{ deploy_root }}"
        state: directory
        owner: user1
        group: user1
        mode: '0755'

    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ deploy_root }}/{{ item.dest }}"
        mode: '0644'
      with_items:
        - { src: "{{ local_root }}/docker-compose.yml", dest: "docker-compose.yml" }
        - { src: "{{ local_root }}/html/index.html", dest: "html/index.html" }
        - { src: "{{ local_root }}/proxy/nginx.conf", dest: "proxy/nginx.conf" }

    - name: Ensure subdirectories exist
      file:
        path: "{{ deploy_root }}/{{ item }}"
        state: directory
        mode: '0755'
        owner: user1
        group: user1
      loop:
        - html
        - proxy

    - name: Restart web cluster
      shell: docker compose down && docker compose up -d
      args:
        chdir: "{{ deploy_root }}"
