---
- hosts: control
  become: true  # root 권한으로 실행
  vars:
    ssh_key_path: "/home/user1/.ssh"
    public_key: "{{ lookup('file', ssh_key_path + '/project.pem.pub') }}"
  tasks:
    # 필수 도구 설치 (Git, curl)
    - name: Install required tools (Git, curl, vim, wget)
      apt:
        name:
          - git
          - curl
          - vim
          - wget
          - sshpass
        state: present 

    # .ssh 디렉터리 먼저 만들기
    - name: Ensure .ssh directory exists with correct permissions
      file:
        path: "{{ ssh_key_path }}"
        state: directory
        mode: '0700'

    # SSH 디렉터리 권한 설정
    - name: Set permissions for .ssh directory
      file:
        path: /home/user1/.ssh
        state: directory
        mode: '0700'

    # SSH 키 생성
    - name: Generate SSH key
      command: ssh-keygen -q -N "" -f "{{ ssh_key_path }}/project.pem"
      args:
        creates: "{{ ssh_key_path }}/project.pem"

    # SSH 키 파일 권한 설정
    - name: Set permissions for SSH private key
      file:
        path: "{{ ssh_key_path }}/project.pem"
        state: file
        mode: '0600'

    # SSH 공개 키 파일 권한 설정
    - name: Set permissions for SSH public key
      file:
        path: "{{ ssh_key_path }}/project.pem.pub"
        state: file
        mode: '0644'

    # .ssh/config 파일 생성 및 설정
    - name: Configure SSH config
      copy:
        dest: /home/user1/.ssh/config
        content: |
          Host web
            HostName 172.16.1.20
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no

          Host db
            HostName 172.16.1.30
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no

          Host storage1
            HostName 172.16.1.40
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no

          Host storage2
            HostName 172.16.1.50
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no

          Host monitoring
            HostName 172.16.1.60
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no

          Host app
            HostName 172.16.1.70
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no
        mode: '0600'

    - name: Ensure .ssh directory exists on remote servers
      ansible.builtin.file:
        path: /home/user1/.ssh
        state: directory
        mode: '0700'
        owner: user1
        group: user1
      delegate_to: "{{ item }}"
      loop:
        - web-server
        - db-server
        - storage-server1
        - storage-server2
        - monitoring-server
        - app-server

    - name: Ensure authorized_keys file exists
      ansible.builtin.file:
        path: /home/user1/.ssh/authorized_keys
        state: touch
        mode: '0600'
        owner: user1
        group: user1
      delegate_to: "{{ item }}"
      loop:
        - web-server
        - db-server
        - storage-server1
        - storage-server2
        - monitoring-server
        - app-server

    - name: Add project public key to authorized_keys
      ansible.builtin.authorized_key:
        user: user1
        state: present
        key: "{{ public_key }}"
      delegate_to: "{{ item }}"
      loop:
        - web-server
        - db-server
        - storage-server1
        - storage-server2
        - monitoring-server
        - app-server


