- name: Node Exporter 설치
  hosts: all:!monitoring
  become: true
  tasks:
    - name: Node Exporter 바이너리 다운로드
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: 압축 해제
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: 심볼릭 링크 생성
      file:
        src: /opt/node_exporter-1.7.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        state: link
        force: yes

    - name: systemd 서비스 등록
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: 서비스 시작 및 활성화
      systemd:
        name: node_exporter
        enabled: yes
        state: started

- name: Docker 기반 모니터링 스택 설치 (Prometheus, Grafana, Alertmanager)
  hosts: monitoring
  become: true
  vars:
    prometheus_targets:
      - web:9100
      - app:9100
      - db:9100
      - storage1:9100
      - storage2:9100
      - control:9100
  tasks:
    - name: Docker & Docker Compose 설치
      apt:
        name: [docker.io, docker-compose]
        state: present
        update_cache: yes

    - name: 모니터링 디렉토리 구성
      file:
        path: /opt/monitoring
        state: directory
        recurse: yes

    - name: Prometheus 설정 파일 배포
      copy:
        dest: /opt/monitoring/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'node_exporters'
              static_configs:
                - targets:
                    {{ prometheus_targets | to_nice_yaml(indent=6) }}

    - name: docker-compose.yml 배포
      copy:
        dest: /opt/monitoring/docker-compose.yml
        content: |
          version: '3'
          services:
            prometheus:
              image: prom/prometheus
              volumes:
                - ./prometheus.yml:/etc/prometheus/prometheus.yml
              ports:
                - "9090:9090"
            grafana:
              image: grafana/grafana
              ports:
                - "3000:3000"
            alertmanager:
              image: prom/alertmanager
              ports:
                - "9093:9093"

    - name: Docker Compose로 스택 실행
      shell: |
        cd /opt/monitoring && docker-compose up -d
