---
- name: Deploy Advanced Monitoring Stack
  hosts: monitoring
  become: true
  vars:
    prometheus_version: "2.43.0"
    node_exporter_version: "1.5.0"
    grafana_version: "9.5.2"
    alertmanager_version: "0.25.0"
    grafana_admin_password: "test123"

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted

    - name: restart alertmanager
      systemd:
        name: alertmanager
        state: restarted

    - name: restart grafana
      systemd:
        name: grafana-server
        state: restarted

  tasks:
    - name: Create monitoring user
      user:
        name: user1
        system: yes
        shell: /bin/bash
        create_home: yes

    - name: Create standard directories
      file:
        path: "{{ item }}"
        state: directory
        owner: user1
        group: user1
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /etc/alertmanager
        - /var/lib/alertmanager

    - name: Install base dependencies
      apt:
        name: ["tar", "net-tools", "software-properties-common"]
        update_cache: yes
        cache_valid_time: 3600

    - name: Deploy Node Exporter locally
      block:
        - name: Download Node Exporter
          get_url:
            url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
            dest: /tmp/node_exporter.tar.gz

        - name: Extract and install
          unarchive:
            src: /tmp/node_exporter.tar.gz
            dest: /usr/local/bin/
            remote_src: yes
            extra_opts: ["--strip-components=1"]
            owner: user1
            group: user1
            mode: '0755'

        - name: Configure systemd service
          copy:
            dest: /etc/systemd/system/node_exporter.service
            content: |
              [Unit]
              Description=Node Exporter
              After=network.target

              [Service]
              User=user1
              ExecStart=/usr/local/bin/node_exporter
              Restart=always

              [Install]
              WantedBy=multi-user.target

        - name: Enable service
          systemd:
            name: node_exporter
            enabled: yes
            state: started
      tags: node_exporter

    - name: Deploy Prometheus
      block:
        - name: Download Prometheus
          get_url:
            url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
            dest: /tmp/prometheus.tar.gz

        - name: Extract and install
          unarchive:
            src: /tmp/prometheus.tar.gz
            dest: /usr/local/bin/
            remote_src: yes
            extra_opts: ["--strip-components=1"]
            owner: user1
            group: user1
            mode: '0755'

        - name: Generate Prometheus scrape targets dynamically
          set_fact:
            prometheus_targets: >-
              {{
                groups['web'] + groups['db'] + groups['storage'] + groups['app']
                | map('extract', hostvars, ['ansible_host'])
                | map('regex_replace', '$', ':9100')
                | list
              }}

        - name: Configure Prometheus
          copy:
            dest: /etc/prometheus/prometheus.yml
            content: |
              global:
                scrape_interval: 15s
              scrape_configs:
                - job_name: 'nodes'
                  static_configs:
                    - targets: {{ prometheus_targets }}
            owner: user1
            group: user1
          notify: restart prometheus

        - name: Configure systemd service
          copy:
            dest: /etc/systemd/system/prometheus.service
            content: |
              [Unit]
              Description=Prometheus Server
              After=network.target

              [Service]
              User=user1
              ExecStart=/usr/local/bin/prometheus \
                --config.file=/etc/prometheus/prometheus.yml \
                --storage.tsdb.path=/var/lib/prometheus
              Restart=always

              [Install]
              WantedBy=multi-user.target

        - name: Enable service
          systemd:
            name: prometheus
            enabled: yes
            state: started
            
        - name: Create alerting rules file
          copy:
            dest: /etc/prometheus/rules.yml
            content: |
              groups:
                - name: node_alerts
                  rules:
                    - alert: HighCPUUsage
                      expr: 100 - (avg by (instance)(rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 90
                      for: 1m
                      labels:
                        severity: warning
                      annotations:
                        summary: "High CPU usage detected on {{ $labels.instance }}"
                        description: "CPU usage is above 90% for 1 minute."
            owner: user1
            group: user1
          notify: restart prometheus

        - name: Add rule_files to Prometheus config
          lineinfile:
            path: /etc/prometheus/prometheus.yml
            insertafter: 'global:'
            line: '  rule_files:\n    - "/etc/prometheus/rules.yml"'
          notify: restart prometheus            
      tags: prometheus

    - name: Deploy Alertmanager
      block:
        - name: Download Alertmanager
          get_url:
            url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
            dest: /tmp/alertmanager.tar.gz

        - name: Extract and install
          unarchive:
            src: /tmp/alertmanager.tar.gz
            dest: /usr/local/bin/
            remote_src: yes
            extra_opts: ["--strip-components=1"]
            owner: user1
            group: user1
            mode: '0755'

        - name: Configure Alertmanager
          copy:
            dest: /etc/alertmanager/alertmanager.yml
            content: |
              route:
                receiver: 'default'
              receivers:
                - name: 'default'
                  webhook_configs:
                  - url: 'http://dummy.webhook'
            owner: user1
            group: user1
          notify: restart alertmanager

        - name: Configure systemd service
          copy:
            dest: /etc/systemd/system/alertmanager.service
            content: |
              [Unit]
              Description=Alertmanager
              After=network.target prometheus.service

              [Service]
              User=user1
              ExecStart=/usr/local/bin/alertmanager \
                --config.file=/etc/alertmanager/alertmanager.yml \
                --storage.path=/var/lib/alertmanager
              Restart=always

              [Install]
              WantedBy=multi-user.target

        - name: Enable service
          systemd:
            name: alertmanager
            enabled: yes
            state: started
      tags: alertmanager

    - name: Deploy Grafana
      block:
        - name: Add Grafana GPG key
          apt_key:
            url: https://packages.grafana.com/gpg.key
            state: present

        - name: Add Grafana repository
          apt_repository:
            repo: "deb https://packages.grafana.com/oss/deb stable main"
            state: present
            update_cache: yes

        - name: Install Grafana
          apt:
            name: "grafana={{ grafana_version }}"
            state: present

        - name: Configure Grafana security
          ini_file:
            path: /etc/grafana/grafana.ini
            section: security
            option: admin_password
            value: "{{ grafana_admin_password }}"
            backup: yes
            mode: 0640
          notify: restart grafana

        - name: Enable service
          systemd:
            name: grafana-server
            enabled: yes
            state: started
      tags: grafana
