---
- name: Deploy Web Front (Nginx)
  hosts: web
  become: true

  vars:
    deploy_root: /home/user1/web_deploy
    local_project_root: ../../infra-components/web
    config_files:
      - docker-compose.yml
    nginx_dir: nginx

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: common

    - name: Create project root directory
      file:
        path: "{{ deploy_root }}"
        state: directory
        owner: user1
        group: user1
        mode: '0755'

    - name: Create nginx config directory
      file:
        path: "{{ deploy_root }}/{{ nginx_dir }}"
        state: directory
        owner: user1
        group: user1
        mode: '0755'

    - name: Copy config files
      copy:
        src: "{{ local_project_root }}/{{ item }}"
        dest: "{{ deploy_root }}/{{ item }}"
        owner: user1
        group: user1
        mode: '0644'
      loop: "{{ config_files }}"

    - name: Copy nginx.conf
      copy:
        src: "{{ local_project_root }}/nginx/nginx.conf"
        dest: "{{ deploy_root }}/nginx/nginx.conf"
        owner: user1
        group: user1
        mode: '0644'

    - name: Stop and remove existing containers
      shell: docker compose down --remove-orphans || true
      args:
        chdir: "{{ deploy_root }}"

    - name: Start nginx container
      shell: docker compose up -d
      args:
        chdir: "{{ deploy_root }}"

