---
- name: DB 환경 준비 
  hosts: db_server
  become: true
  vars:
    db_port: 5432
    nfs_server_ip: "211.183.3.40"
    nfs_shared_dir: "/shared/db"
    local_mount_dir: "/db_data"

  tasks:


    - name: NFS 클라이언트 패키지 설치
      apt:
        name: nfs-common
        state: present
      tags: nfs

    - name: 마운트 디렉토리 생성
      file:
        path: "{{ local_mount_dir }}"
        state: directory
        owner: user1
        group: user1
        mode: '0755'
      tags: nfs

    - name: NFS 마운트
      mount:
        src: "{{ nfs_server_ip }}:{{ nfs_shared_dir }}"
        path: "{{ local_mount_dir }}"
        fstype: nfs
        opts: defaults
        state: mounted
      tags: nfs

    - name: DB 포트 방화벽 오픈
      ufw:
        rule: allow
        port: "{{ db_port }}"
        proto: tcp
      tags: firewall