---
- name: Deploy Web Cluster with Proxy
  hosts: web
  become: true

  vars:
    deploy_root: /home/user1/web_deploy
    local_project_root: ../../infra-components/web
    web_files:
      - { src: "docker-compose.yml", dest: "docker-compose.yml" }
      - { src: "html/index.html", dest: "html/index.html" }
      - { src: "proxy/nginx.conf", dest: "proxy/nginx.conf" }
    subdirectories:
      - html
      - proxy

  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: common

    - name: Create deployment directory
      file:
        path: "{{ deploy_root }}"
        state: directory
        owner: user1
        group: user1
        mode: '0755'

    - name: Ensure subdirectories exist
      file:
        path: "{{ deploy_root }}/{{ item }}"
        state: directory
        mode: '0755'
        owner: user1
        group: user1
      loop: "{{ subdirectories }}"

    - name: Copy files
      copy:
        src: "{{ local_project_root }}/{{ item.src }}"
        dest: "{{ deploy_root }}/{{ item.dest }}"
        owner: user1
        group: user1
        mode: '0644'
      loop: "{{ web_files }}"

    - name: Restart web cluster
      shell: docker compose down && docker compose up -d
      args:
        chdir: "{{ deploy_root }}"