---
- hosts: control
  become: true  # root 권한으로 실행
  vars:
    ssh_key_path: "/home/user1/.ssh"
  tasks:
    # .ssh 디렉터리 먼저 만들기
    - name: Ensure .ssh directory exists with correct permissions
      file:
        path: "{{ ssh_key_path }}"
        state: directory
        mode: '0700'

    # SSH 디렉터리 권한 설정
    - name: Set permissions for .ssh directory
      file:
        path: /home/user1/.ssh
        state: directory
        mode: '0700'

    # SSH 키 생성
    - name: Generate SSH key
      command: ssh-keygen -q -N "" -f "{{ ssh_key_path }}/project.pem"
      args:
        creates: "{{ ssh_key_path }}/project.pem"

    # SSH 키 파일 권한 설정
    - name: Set permissions for SSH private key
      file:
        path: "{{ ssh_key_path }}/project.pem"
        state: file
        mode: '0600'

    # SSH 공개 키 파일 권한 설정
    - name: Set permissions for SSH public key
      file:
        path: "{{ ssh_key_path }}/project.pem.pub"
        state: file
        mode: '0644'

    # .ssh/config 파일 생성 및 설정
    - name: Configure SSH config
      copy:
        dest: /home/user1/.ssh/config
        content: |
          Host web
            HostName 211.183.3.20
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no

          Host db
            HostName 211.183.3.30
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no

          Host storage
            HostName 211.183.3.40
            User user1
            IdentityFile /home/user1/.ssh/project.pem
            StrictHostKeyChecking no
        mode: '0600'

    - name: Ensure .ssh directory exists with correct permissions
      delegate_to: "{{ item }}"
      ansible.builtin.authorized_key:
        state: present
        key: "{{ lookup('file', ssh_key_path + '/project.pem.pub') }}"
      loop:
        - web
        - db
        - storage

    # 필수 도구 설치 (Git, curl)
    - name: Install required tools (Git, curl, vim, wget)
      apt:
        name:
          - git
          - curl
          - vim
          - wget
        state: present 
