global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: 'alex941@naver.com'
        from: 'alex941song@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alex941song@gmail.com'
        auth_password: 'dvjuebtbrylkyzlm'
        require_tls: true
