all:
  children:
    control:
      hosts:
        control:
          ansible_host: 192.168.3.41
    
    web:
      hosts:
        web:
          ansible_host: 211.183.3.20
    
    db:
      hosts:
        db:
          ansible_host: 211.183.3.30

    storage:
      hosts:
        storage-server:
          ansible_host: 211.183.3.40