all:
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local

    web:
      hosts:
        web-server:
          ansible_host: 172.16.1.20
          ansible_user: user1
          ansible_ssh_pass: user1

    db:
      hosts:
        db-server:
          ansible_host: 172.16.1.30
          ansible_user: user1
          ansible_ssh_pass: user1

    storage:
      hosts:
        storage-server:
          ansible_host: 172.16.1.40
          ansible_user: user1
          ansible_ssh_pass: user1

    storage2:
      hosts:
        storage2-server:
          ansible_host: 172.16.1.50
          ansible_user: user1
          ansible_ssh_pass: user1
          
    monitoring:
      hosts:
        monitoring:-server:
          ansible_host: 172.16.1.60
          ansible_user: user1
          ansible_ssh_pass: user1