all:
  children:
    control:
      hosts:
        control-server:
          ansible_host: 211.183.3.10
    
    web:
      hosts:
        web-server:
          ansible_host: 211.183.3.20
    
    db:
      hosts:
        db-server:
          ansible_host: 211.183.3.30

    storage:
      hosts:
        storage-server:
          ansible_host: 211.183.3.40