all:
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: 127.0.0.1

    web:
      hosts:
        web-server:
          ansible_host: 172.16.1.20
          ansible_user: user1
          ansible_ssh_pass: user1

    db:
      hosts:
        db-server:
          ansible_host: 172.16.1.30
          ansible_user: user1
          ansible_ssh_pass: user1

    storage:
      hosts:
        storage-server1:
          ansible_host: 172.16.1.40
          ansible_user: user1
          ansible_ssh_pass: user1
        storage-server2:
          ansible_host: 172.16.1.50
          ansible_user: user1
          ansible_ssh_pass: user1

    monitoring:
      hosts:
        monitoring-server:
          ansible_host: 172.16.1.60
          ansible_user: user1
          ansible_ssh_pass: user1

    app:
      hosts:
        app-server:
          ansible_host: 172.16.1.70
          ansible_user: user1
          ansible_ssh_pass: user1